### ISSUE TITLE
客户端im连接快点更新呀

### ISSUE THREAD

**Issue by chenweihaoone** [Madou-Shinni/kratos-im#1]
![image](https://github.com/Madou-Shinni/kratos-im/assets/94281320/3ed8206c-0264-43c0-a978-b35a25713f3a)
这一块怎么连都连不上

**Comment by chenweihaoone** [comment]
![image](https://github.com/Madou-Shinni/kratos-im/assets/94281320/d57a2b38-7327-4bf2-b2ea-0942a22d8100)

**Comment by chenweihaoone** [comment]
![image](https://github.com/Madou-Shinni/kratos-im/assets/94281320/7305e7a4-4292-47c2-b445-7b199faa42d4)
看job那边连的方式终于连上辣

**Comment by Madou-Shinni** [comment]
> ![image](https://private-user-images.githubusercontent.com/94281320/328936185-3ed8206c-0264-43c0-a978-b35a25713f3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTc1NTIsIm5iZiI6MTcxNTI1NzI1MiwicGF0aCI6Ii85NDI4MTMyMC8zMjg5MzYxODUtM2VkODIwNmMtMDI2NC00M2MwLWE5NzgtYjM1YTI1NzEzZjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEyMjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYzk5YjM4MWM2ZDRhNjEwMTY3ZGE4MmU1OTc1YzEwOTZiY2Y3MjM4ODY5OTA1MGQ3Yjg0NDgwMjFlMWUyMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EXP-NTGzp99nQvXGXSJo0beae1a-G3fuxbJOEBh2KLQ) 这一块怎么连都连不上

很高兴能够看到你的提问，其实我在当天晚上看到了来自你的提问，但是因为最近的事情让我陷入了疲惫的漩涡，我将尽可能得给你展示客户端的连接以及通讯方式，希望你能得到帮助

1. 建立连接

你需要在请求头带上token认证成功，完成连接处理

![image](https://github.com/Madou-Shinni/kratos-im/assets/91399492/e0c2e2b0-6a6a-4306-a149-aed107e95124)

2. 发送与接收

发送消息

![image](https://github.com/Madou-Shinni/kratos-im/assets/91399492/2a49e700-8eef-4ff6-87e6-9a55a3f993ab)

接收消息

![image](https://github.com/Madou-Shinni/kratos-im/assets/91399492/a19b8782-4916-4a14-9854-8e48809a4fd4)

**Comment by chenweihaoone** [comment]
> > ![image](https://private-user-images.githubusercontent.com/94281320/328936185-3ed8206c-0264-43c0-a978-b35a25713f3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTc1NTIsIm5iZiI6MTcxNTI1NzI1MiwicGF0aCI6Ii85NDI4MTMyMC8zMjg5MzYxODUtM2VkODIwNmMtMDI2NC00M2MwLWE5NzgtYjM1YTI1NzEzZjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEyMjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYzk5YjM4MWM2ZDRhNjEwMTY3ZGE4MmU1OTc1YzEwOTZiY2Y3MjM4ODY5OTA1MGQ3Yjg0NDgwMjFlMWUyMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EXP-NTGzp99nQvXGXSJo0beae1a-G3fuxbJOEBh2KLQ) 这一块怎么连都连不上
> 
> 很高兴能够看到你的提问，其实我在当天晚上看到了来自你的提问，但是因为最近的事情让我陷入了疲惫的漩涡，我将尽可能得给你展示客户端的连接以及通讯方式，希望你能得到帮助
> 
> 1. 建立连接
> 
> 你需要在请求头带上token认证成功，完成连接处理
> 
> ![image](https://private-user-images.githubusercontent.com/91399492/329245844-e0c2e2b0-6a6a-4306-a149-aed107e95124.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTg5ODEsIm5iZiI6MTcxNTI1ODY4MSwicGF0aCI6Ii85MTM5OTQ5Mi8zMjkyNDU4NDQtZTBjMmUyYjAtNmE2YS00MzA2LWExNDktYWVkMTA3ZTk1MTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEyNDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMjNjOWQyNGE1ZTZhYjlmMTUyODZlYmI4Yzc2ZjlkMDMxNmIwN2IwMjk0MTQ0ZTk3NmZkMDA3NzcyMGQ0NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m2a1bb618Lv4nQiX76I1Ko_ZESIFVM_z0rDdszzWzsM)
> 
> 2. 发送与接收
> 
> 发送消息
> 
> ![image](https://private-user-images.githubusercontent.com/91399492/329247805-2a49e700-8eef-4ff6-87e6-9a55a3f993ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTg5ODEsIm5iZiI6MTcxNTI1ODY4MSwicGF0aCI6Ii85MTM5OTQ5Mi8zMjkyNDc4MDUtMmE0OWU3MDAtOGVlZi00ZmY2LTg3ZTYtOWE1NWEzZjk5M2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEyNDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNWI1YjNiZmYwMGJlN2MxOTY0MWU4MTUxOWUyZjNjMzVmNzlmNTgzZjhkNmVmMmM4NmVmNDRlNmMwNTAzODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kx3dti4rPs4A7JGkUAJ9lwds3_7SIFzYEw52nKGLZJk)
> 
> 接收消息
> 
> ![image](https://private-user-images.githubusercontent.com/91399492/329247962-a19b8782-4916-4a14-9854-8e48809a4fd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTg5ODEsIm5iZiI6MTcxNTI1ODY4MSwicGF0aCI6Ii85MTM5OTQ5Mi8zMjkyNDc5NjItYTE5Yjg3ODItNDkxNi00YTE0LTk4NTQtOGU0ODgwOWE0ZmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEyNDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNTI5Y2VlNWU1MWVmNGVmNjA2ZWU0YzAyNzFjYTI2NjNmMmY3OWJlZDg5Mjk4ZjBiZGE1NGQ5Mzk4ZDA3MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1bRSH4BKDQNPRBhL4sBKHZezghbbI3fw0KTEWRCAsxc)

感谢作者的解答，连上了
